import { useState, useCallback } from "react";
import { useWallet, useConnection } from "@solana/wallet-adapter-react";
import * as anchor from "@coral-xyz/anchor";
import { Program } from "@coral-xyz/anchor";
import { x25519, RescueCipher, getMXEPublicKey } from "@arcium-hq/client";
import * as snarkjs from "snarkjs";
import { randomBytes } from "crypto";
import { CONFIG } from "../config";

export type VerifierStage = "idle" | "exchanging" | "encrypting" | "proving" | "verifying" | "success" | "error";

export function useZkVerifier() {
  const [stage, setStage] = useState<VerifierStage>("idle");
  const [error, setError] = useState<string | null>(null);
  const [logs, setLogs] = useState<string[]>([]);
  
  const { publicKey, signTransaction } = useWallet();
  const { connection } = useConnection();

  const addLog = useCallback((msg: string) => {
    setLogs((prev) => [...prev, `[${new Date().toLocaleTimeString()}] ${msg}`]);
  }, []);

  const verifyCompliance = async (age: number) => {
    if (!publicKey || !signTransaction) {
      setError("Wallet not connected");
      return;
    }

    setStage("exchanging");
    setError(null);
    setLogs([]);

    try {
      addLog("Starting Key Exchange with Arcium MXE...");
      const privateKey = x25519.utils.randomSecretKey();
      const clientPublicKey = x25519.getPublicKey(privateKey);
      
      const provider = new anchor.AnchorProvider(connection, { publicKey, signTransaction } as any, {});
      const mxePublicKey = await getMXEPublicKey(provider, CONFIG.SOLANA.ARCIUM_PROGRAM_ID);
      
      const sharedSecret = x25519.getSharedSecret(privateKey, mxePublicKey);
      const cipher = new RescueCipher(sharedSecret);
      addLog("Shared secret derived successfully.");

      setStage("encrypting");
      addLog("Shielding input using RescueCipher...");
      const nonce = randomBytes(16);
      const ciphertext = cipher.encrypt([BigInt(age)], nonce);
      addLog(`Ciphertext generated (nonce: ${nonce.toString("hex").substring(0, 8)}...)`);

      setStage("proving");
      addLog("Generating Zero-Knowledge Proof locally (Groth16)...");
      const { proof, publicSignals } = await snarkjs.groth16.fullProve(
        { age: age },
        CONFIG.ZK.WASM_PATH,
        CONFIG.ZK.ZKEY_PATH
      );
      addLog("SNARK Proof generated successfully.");

      setStage("verifying");
      addLog("Submitting proof to Solana Devnet...");
      
      // IDL would normally be generated by anchor build
      const program = new Program({ address: CONFIG.SOLANA.PROGRAM_ID.toString(), metadata: { name: "zkverifier" }, instructions: [{ name: "verifyProof", accounts: [], args: [] }] } as any, provider);

      const [verificationState] = anchor.web3.PublicKey.findProgramAddressSync(
        [Buffer.from("verification"), publicKey.toBuffer()],
        program.programId
      );

      // Packing logic (reused from previous implementation but optimized)
      const proofA = packProofPoint(proof.pi_a.slice(0, 2));
      const proofB = packProofPointB(proof.pi_b.slice(0, 2));
      const proofC = packProofPoint(proof.pi_c.slice(0, 2));
      const publicInputs = publicSignals.map((sig: string) => packPublicInput(sig));

      await (program.methods as any)
        .verifyProof(
          Array.from(proofA),
          Array.from(proofB),
          Array.from(proofC),
          publicInputs.map((i: any) => Array.from(i))
        )
        .accounts({
          verificationState,
          verifierState: CONFIG.SOLANA.VERIFIER_STATE,
          signer: publicKey,
          systemProgram: anchor.web3.SystemProgram.programId,
        })
        .rpc();

      addLog("Solana on-chain verification successful.");
      setStage("success");
    } catch (err: any) {
      console.error(err);
      setError(err.message || "An unexpected error occurred");
      setStage("error");
      addLog(`ERROR: ${err.message}`);
    }
  };

  return { stage, error, logs, verifyCompliance };
}

// Helpers for proof packing
function packProofPoint(point: string[]): Uint8Array {
  const bytes = new Uint8Array(64);
  bytes.set(anchor.utils.bytes.hex.decode(BigInt(point[0]).toString(16).padStart(64, '0')), 0);
  bytes.set(anchor.utils.bytes.hex.decode(BigInt(point[1]).toString(16).padStart(64, '0')), 32);
  return bytes;
}

function packProofPointB(point: string[][]): Uint8Array {
  const bytes = new Uint8Array(128);
  bytes.set(anchor.utils.bytes.hex.decode(BigInt(point[0][0]).toString(16).padStart(64, '0')), 0);
  bytes.set(anchor.utils.bytes.hex.decode(BigInt(point[0][1]).toString(16).padStart(64, '0')), 32);
  bytes.set(anchor.utils.bytes.hex.decode(BigInt(point[1][0]).toString(16).padStart(64, '0')), 64);
  bytes.set(anchor.utils.bytes.hex.decode(BigInt(point[1][1]).toString(16).padStart(64, '0')), 96);
  return bytes;
}

function packPublicInput(signal: string): Uint8Array {
  return anchor.utils.bytes.hex.decode(BigInt(signal).toString(16).padStart(64, '0'));
}
